### numpy 
#### we have numpy in c++ why numpy

In [ ]:
import numpy as np

In [ ]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
#creating arra from list
import numpy as np
num_arr=np.array([1,2,3,4,5])
print("1d arra:",num_arr)
print("one 1d array")

1d arra: [1 2 3 4 5]
one 1d array


In [6]:
# creating 2d array
arr_2d=np.array([[2,3,4,5],[3,4,5,6]])
print("2d arra",arr_2d)

2d arra [[2 3 4 5]
 [3 4 5 6]]


## list vs numpy array

In [7]:
py_lst=[2,3,4]
print("python list multiplication",py_lst * 2)

python list multiplication [2, 3, 4, 2, 3, 4]


In [8]:
np_lst=np.array([2,3,4]) #element wise multiplication
print("python list multiplication",np_lst * 2)

python list multiplication [4 6 8]


In [9]:
import time 
start=time.time()
py_list=[i*2 for i in range(100000)]
print("\n list operation time:",time.time()-start)


 list operation time: 0.004632711410522461


start=time.time()
np_arra=np.array()

# creating array from scratch

In [14]:
ones=np.ones((2,3))
print("one array: \n",ones)

one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
zeros=np.zeros((3,4))
print("zeros arra: \n",zeros)

zeros arra: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
full=np.full((2,2),7)
print("full array :\n",full)

full array :
 [[7 7]
 [7 7]]


In [19]:
random=np.random.random((2,3))
print("randome array: \n",random)

randome array: 
 [[0.01366157 0.08646281 0.47906055]
 [0.49885852 0.42400159 0.65769999]]


In [21]:
sequence=np.arange(0,10,2)
print("sequence arra: \n",sequence)

sequence arra: 
 [0 2 4 6 8]


# vector,matrix and tensor

In [22]:
vector=np.array([1,2,3,4])
print("vector:",vector)

vector: [1 2 3 4]


In [23]:
matrix=np.array([[1,2,3,4],[4,5,6,7]])
print("matrix: ",matrix)

matrix:  [[1 2 3 4]
 [4 5 6 7]]


In [26]:
tensor=np.array([
    [[1,2],[3,4],[3,4]],[[2,3],[5,6],[3,5]]])
print("tensor:\n",tensor)

tensor:
 [[[1 2]
  [3 4]
  [3 4]]

 [[2 3]
  [5 6]
  [3 5]]]


# array properties 

arr=np.array([[1,2,3],[4,5,6]])
print("shape",arr.shape)
print("Dimension",arr.ndim)
print("size",arr.size)
print("Dtype",arr.dtype)


# array Reshaping

In [30]:
arr=np.arange(12)
print("original array ", arr)

original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [31]:
reshaped=arr.reshape((3,4))
print("\n Reshaped array",reshaped)


 Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [32]:
flattened=reshaped.flatten()
print("\n ravelved array",flattened)


 ravelved array [ 0  1  2  3  4  5  6  7  8  9 10 11]


# ravel (return view ,insted of copy )

In [33]:
raveled=reshaped.ravel()
print("\n raveled array", raveled)


 raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]


# transpose 

In [35]:
transpose=reshaped.T
print("\n transposed array",transpose)


 transposed array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


# numpy array operation.


In [5]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("basic slicing",arr[2:7])

basic slicing [3 4 5 6 7]


In [4]:
print("with step",arr[1:8:2])


with step [2 4 6 8]


In [6]:
print("negative indexing",arr[-3])

negative indexing 8


## sorting 

In [7]:
unsorted=np.array([3,1,4,1,5,9,2,6])
print("sorted array",np.sort(unsorted))

sorted array [1 1 2 3 4 5 6 9]


In [16]:
import numpy as np
arr_2d_unsorted=np.array([[1,3],[1,3],[2,3]])
print("sorted 2d array by column",np.sort(arr_2d_unsorted))

sorted 2d array by column [[1 3]
 [1 3]
 [2 3]]


# find out monthly sales analysis  min,max,average

In [40]:
###### \
import numpy as np

# Month names
months = np.array([
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
])

sales = []

print("Enter the sales for each month:")
for month in months:
    value = float(input(f"{month}: "))
    sales.append(value)

# Convert list to NumPy array
sales = np.array(sales)

print("\n--- Company Sales Analysis ---")

# Calculations
total_sales = np.sum(sales)
average_sales = np.mean(sales)
highest_sales = np.max(sales)
lowest_sales = np.min(sales)

best_month = months[np.argmax(sales)]
worst_month = months[np.argmin(sales)]

above_avg_months = months[sales > average_sales]
below_avg_months = months[sales < average_sales]

# Output
print(f"Total sales of the year: {total_sales} $")
print(f"Average monthly sales: {average_sales} $")
print(f"Highest sales: {highest_sales} $")
print(f"Lowest sales: {lowest_sales} $")
print(f"Best month: {best_month}")
print(f"Worst month: {worst_month}")
print(f"Above average months: {above_avg_months}")
print(f"Below average months: {below_avg_months}")


Enter the sales for each month:


Jan:  9000
Feb:  999
Mar:  88
Apr:  99
May:  99
Jun:  99
Jul:  99
Aug:  9
Sep:  9
Oct:  9
Nov:  99999
Dec:  999



--- Company Sales Analysis ---
Total sales of the year: 111508.0 $
Average monthly sales: 9292.333333333334 $
Highest sales: 99999.0 $
Lowest sales: 9.0 $
Best month: Nov
Worst month: Aug
Above average months: ['Nov']
Below average months: ['Jan' 'Feb' 'Mar' 'Apr' 'May' 'Jun' 'Jul' 'Aug' 'Sep' 'Oct' 'Dec']


In [3]:
# manipulation data 

## manipulation data

# pandas
## read csv ,json and excel file 

In [26]:
pip install pandas


Note: you may need to restart the kernel to use updated packages.


In [117]:
import pandas as pd
print("printing csv data")
df_csv = pd.read_csv(r"C:\Users\Admin\Desktop\sales_data_sample.csv",encoding="latin1")
print("csv data")
df_json = pd.read_json(r"C:\Users\Admin\Desktop\sample_Data.json",encoding="latin1")

print(df)



printing csv data
csv data
      Name  age Department Section
0    Geeta   20        CSE       A
1  Pallavi   18         EC       B
2    Aishu   25         ME       A


In [30]:
import pandas as pd
data={

    "Name":["Geeta","Shyam","Ghanshyam"],
    "Age":[10,20,30],
    "City":["Nagpur","Mumbai","Delhi"]
}
df=pd.DataFrame(data)
print(df)

# df.to_csv("output.csv")
df.to_csv("output.csv",index=False)

        Name  Age    City
0      Geeta   10  Nagpur
1      Shyam   20  Mumbai
2  Ghanshyam   30   Delhi


## create dataframe and save in csv,json and excel

In [82]:
import pandas as pd

data = {
    "Name": ["Geeta", "Shyam", "Ghanshyam"],
    "Age": [10, 20, 30],
    "City": ["Nagpur", "Mumbai", "Delhi"]
}

df = pd.DataFrame(data)
  # index removed from display

df.to_excel("output.xlsx", index=False)
print(df)

        Name  Age    City
0      Geeta   10  Nagpur
1      Shyam   20  Mumbai
2  Ghanshyam   30   Delhi


In [36]:
import pandas as pd
data={
    "Name":["Geeta","Pallavi","Aishu"],
    "age":[20,18,25],
    "Department":["CSE","EC","ME"],
    "Section":["A","B","A"]
}
df=pd.DataFrame(data)
print(df)
df.to_json("output.json",orient="records")
print("created file")

      Name  age Department Section
0    Geeta   20        CSE       A
1  Pallavi   18         EC       B
2    Aishu   25         ME       A
created file


In [120]:
import pandas as pd
data={
    "Name":["Geeta","Pallavi","Aishu"],
    "age":[20,18,25],
    "Department":["CSE","EC","ME"],
    "Section":["A","B","A"]
}
df=pd.DataFrame(data)
print(df.info())
df.to_json("outputwithoutorient.json",indent=4)
print("created file")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Name        3 non-null      object
 1   age         3 non-null      int64 
 2   Department  3 non-null      object
 3   Section     3 non-null      object
dtypes: int64(1), object(3)
memory usage: 228.0+ bytes
None
created file


### . 1-understand the data set
### . identify the problems (missing value)
### . plan next steps
####  head display five row from head and tail 

In [118]:
import pandas as pd
df_json = pd.read_json(r"C:\Users\Admin\Desktop\sample_Data.json",encoding="latin1")

print(df_json.tail(2))
print(df_json.head(2))

    id                              name  \
18  19  Ninja Foodi Digital Air Fry Oven   
19  20  Cuisinart ICE-70 Ice Cream Maker   

                                          description   price        category  \
18  The Ninja Foodi Digital Air Fry Oven features ...  209.99  Home & Kitchen   
19  The Cuisinart ICE-70 Ice Cream Maker features ...  139.99  Home & Kitchen   

                                                image  
18  https://www.ninjakitchen.com/static/img/produc...  
19  https://www.cuisinart.com/share/images/product...  
   id                name                                        description  \
0   1     Apple iPhone 12  The Apple iPhone 12 features a 6.1-inch Super ...   
1   2  Samsung Galaxy S21  The Samsung Galaxy S21 features a 6.2-inch Dyn...   

   price     category                                              image  
0  999.0  Electronics  https://www.apple.com/newsroom/images/product/...  
1  799.0  Electronics  https://images.samsung.com/is/image/samsu

### before start any of the operation we need to clean data or manipulation
### how to row and column to check how many 
### understand missing value 
### understand type of data 
### number of rows and column name
### non null count 
### memory usage of large data 


In [119]:
import pandas as pd
df_data = pd.read_json(r"C:\Users\Admin\Desktop\sample_Data.json",encoding="latin1")
print(df.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Name        3 non-null      object
 1   age         3 non-null      int64 
 2   Department  3 non-null      object
 3   Section     3 non-null      object
dtypes: int64(1), object(3)
memory usage: 228.0+ bytes
None


# describe sample data frame
# 

In [126]:
import pandas as pd
data={
    "Name":['Geeta','Viahsu','Ghynshyam','Megha','kavita'],
    "Age":[26,27,28,28,25]
}
df_data_describe=pd.DataFrame(data)
print("sample data frame")
print(df_data_describe)
print("descriptive statistics")
print(df_data_describe.describe())


sample data frame
descriptive statistics
        Name  Age
0      Geeta   26
1     Viahsu   27
2  Ghynshyam   28
3      Megha   28
4     kavita   25
            Age
count   5.00000
mean   26.80000
std     1.30384
min    25.00000
25%    26.00000
50%    27.00000
75%    28.00000
max    28.00000


# how big is your data?
# what are the names of columns ?
# to solve this shape is attribute will come to know column name (number of row and number of column it returns in tuple )

In [128]:
import pandas as pd
data={
    "Name":['Geeta','Viahsu','Ghynshyam','Megha','kavita'],
    "Age":[26,27,28,28,25]
}
df=pd.DataFrame(data)
print(df)
print(f'Shape:{df.shape}')
print(f'Column Names:{df.columns}')

        Name  Age
0      Geeta   26
1     Viahsu   27
2  Ghynshyam   28
3      Megha   28
4     kavita   25
Shape:(5, 2)
Column Names:Index(['Name', 'Age'], dtype='object')


# how to select specific column-a series ,multiple columns of data dataframe
# filter rows-b-filter_row----   filtered_row=df[df["columns"]>50000]
# filter multiple rows----  filtered_row=df[(df["salary"]>5000])&(df["column2"]<4000)]
# comibne multiple conditions 


In [133]:
import pandas as pd
emp_data={
    "Name":['Ram','shyam','Ghanshyam','Dhanshyam','Aditu','Jagadish','Raj','Simran'],
    "Age":[28,34,22,30,29,40,25,32],
    "Salary":[50000,60000,45000,52000,49000,70000,480000,58000],
    "Performance Score":[85,90,78,92,88,95,80,89]
}
df=pd.DataFrame(emp_data)
print(df)
print("single filtering")
name=df['Name']
print(name)
print("filtering Multiple columns")
subset=df[["Name","Salary"]]
print(subset)

        Name  Age  Salary  Performance Score
0        Ram   28   50000                 85
1      shyam   34   60000                 90
2  Ghanshyam   22   45000                 78
3  Dhanshyam   30   52000                 92
4      Aditu   29   49000                 88
5   Jagadish   40   70000                 95
6        Raj   25  480000                 80
7     Simran   32   58000                 89
single filtering
0          Ram
1        shyam
2    Ghanshyam
3    Dhanshyam
4        Aditu
5     Jagadish
6          Raj
7       Simran
Name: Name, dtype: object
filtering Multiple columns
        Name  Salary
0        Ram   50000
1      shyam   60000
2  Ghanshyam   45000
3  Dhanshyam   52000
4      Aditu   49000
5   Jagadish   70000
6        Raj  480000
7     Simran   58000


# filtering rows
# filtering single row
# filtering multiple rows


In [145]:
import pandas as pd
emp_data={
    "Name":['Ram','shyam','Ghanshyam','Dhanshyam','Aditu','Jagadish','Raj','Simran'],
    "Age":[28,34,22,30,29,40,25,32],
    "Salary":[50000,60000,45000,52000,49000,70000,480000,58000],
    "Performance_Score":[85,90,78,92,88,95,80,89]
}
df=pd.DataFrame(emp_data)
high_salary=df[df['Salary']>50000]
print('Employee With Salary > 50000')
print(high_salary)

# filtering rows salary > 50k and age>30
print("filtering multiple rows")
filtered=df[(df['Age']>30) & (df['Salary']>50000)]
print(filtered)
# using or conditions
print('Employees older than 35 OR performance score >90')
filtered_or=df[(df['Age']>35)| (df['Performance_Score']>90)]


Employee With Salary > 50000
        Name  Age  Salary  Performance_Score
1      shyam   34   60000                 90
3  Dhanshyam   30   52000                 92
5   Jagadish   40   70000                 95
6        Raj   25  480000                 80
7     Simran   32   58000                 89
filtering multiple rows
       Name  Age  Salary  Performance_Score
1     shyam   34   60000                 90
5  Jagadish   40   70000                 95
7    Simran   32   58000                 89
Employees older than 35 OR performance score >90


In [4]:
import pandas as pd
mani_data={
    "Name":['Ram','shyam','Ghanshyam','Dhanshyam','Aditu','Jagadish','Raj','Simran'],
    "Age":[28,34,22,30,29,40,25,32],
    "Salary":[50000,60000,45000,52000,49000,70000,480000,58000],
    "Performance_Score":[85,90,78,92,88,95,80,89]
}
df=pd.DataFrame(mani_data)
df["Bonus"]=df['Salary']*0.1
print(df)



        Name  Age  Salary  Performance_Score    Bonus
0        Ram   28   50000                 85   5000.0
1      shyam   34   60000                 90   6000.0
2  Ghanshyam   22   45000                 78   4500.0
3  Dhanshyam   30   52000                 92   5200.0
4      Aditu   29   49000                 88   4900.0
5   Jagadish   40   70000                 95   7000.0
6        Raj   25  480000                 80  48000.0
7     Simran   32   58000                 89   5800.0


## insert()
## df.insert(loc,"column_name","same_data") 

In [5]:
df.insert(0,"Employee Id",[10,20,30,40,50,60,70,80])
print(df)

   Employee Id       Name  Age  Salary  Performance_Score    Bonus
0           10        Ram   28   50000                 85   5000.0
1           20      shyam   34   60000                 90   6000.0
2           30  Ghanshyam   22   45000                 78   4500.0
3           40  Dhanshyam   30   52000                 92   5200.0
4           50      Aditu   29   49000                 88   4900.0
5           60   Jagadish   40   70000                 95   7000.0
6           70        Raj   25  480000                 80  48000.0
7           80     Simran   32   58000                 89   5800.0


### increasing salary by 5%

In [6]:
df['Salary']=df['Salary']*1.05
print(df)

   Employee Id       Name  Age    Salary  Performance_Score    Bonus
0           10        Ram   28   52500.0                 85   5000.0
1           20      shyam   34   63000.0                 90   6000.0
2           30  Ghanshyam   22   47250.0                 78   4500.0
3           40  Dhanshyam   30   54600.0                 92   5200.0
4           50      Aditu   29   51450.0                 88   4900.0
5           60   Jagadish   40   73500.0                 95   7000.0
6           70        Raj   25  504000.0                 80  48000.0
7           80     Simran   32   60900.0                 89   5800.0


In [10]:
# Drop column 
#df.drop(columns=["columnname"],inplace=True)
import pandas as pd
mani_data={
    "Name":['Ram','shyam','Ghanshyam','Dhanshyam','Aditu','Jagadish','Raj','Simran'],
    "Age":[28,34,22,30,29,40,25,32],
    "Salary":[50000,60000,45000,52000,49000,70000,480000,58000],
    "Performance_Score":[85,90,78,92,88,95,80,89]
}
df=pd.DataFrame(mani_data)
df.drop(columns=["Performance_Score","Age"],inplace=True)
print(df)

        Name  Salary
0        Ram   50000
1      shyam   60000
2  Ghanshyam   45000
3  Dhanshyam   52000
4      Aditu   49000
5   Jagadish   70000
6        Raj  480000
7     Simran   58000


In [ ]:
#drop multiple columns

import pandas as pd
mani_data={
    "Name":['Ram','shyam','Ghanshyam','Dhanshyam','Aditu','Jagadish','Raj','Simran'],
    "Age":[28,34,22,30,29,40,25,32],
    "Salary":[50000,60000,45000,52000,49000,70000,480000,58000],
    "Performance_Score":[85,90,78,92,88,95,80,89]
}
df=pd.DataFrame(mani_data)
df.drop(columns=["Performance_Score","Age"],inplace=True)
print(df)

In [13]:
# how to handle missing value
# NaN (not a number)
# None(for object data types)
# isnull() two methods true and false 
# true means there are missing values 
#false means there some missing values
import pandas as pd
mani_data={
    "Name":['Ram',None,'Ghanshyam','Dhanshyam','Aditu','Jagadish','Raj','Simran'],
    "Age":[28,None,22,30,29,40,25,32],
    "Salary":[50000,None,45000,52000,49000,70000,480000,58000],
    "Performance_Score":[85,None,78,92,88,95,80,89]
}
df=pd.DataFrame(mani_data)
print(df)
print(df.isnull())
print(df.isnull().sum())

        Name   Age    Salary  Performance_Score
0        Ram  28.0   50000.0               85.0
1       None   NaN       NaN                NaN
2  Ghanshyam  22.0   45000.0               78.0
3  Dhanshyam  30.0   52000.0               92.0
4      Aditu  29.0   49000.0               88.0
5   Jagadish  40.0   70000.0               95.0
6        Raj  25.0  480000.0               80.0
7     Simran  32.0   58000.0               89.0
    Name    Age  Salary  Performance_Score
0  False  False   False              False
1   True   True    True               True
2  False  False   False              False
3  False  False   False              False
4  False  False   False              False
5  False  False   False              False
6  False  False   False              False
7  False  False   False              False
Name                 1
Age                  1
Salary               1
Performance_Score    1
dtype: int64


In [15]:
# how to handle missing value 
# one way is drop the value if its not necessary without that value use #dropna()
import pandas as pd
mani_data={
    "Name":['Ram',None,'Ghanshyam','Dhanshyam','Aditu','Jagadish','Raj','Simran'],
    "Age":[28,None,22,30,29,40,25,32],
    "Salary":[50000,None,45000,52000,49000,70000,480000,58000],
    "Performance_Score":[85,None,78,92,88,95,80,89]
}
df=pd.DataFrame(mani_data)
print(df)
df.dropna(inplace=True)
print(df)


        Name   Age    Salary  Performance_Score
0        Ram  28.0   50000.0               85.0
1       None   NaN       NaN                NaN
2  Ghanshyam  22.0   45000.0               78.0
3  Dhanshyam  30.0   52000.0               92.0
4      Aditu  29.0   49000.0               88.0
5   Jagadish  40.0   70000.0               95.0
6        Raj  25.0  480000.0               80.0
7     Simran  32.0   58000.0               89.0
        Name   Age    Salary  Performance_Score
0        Ram  28.0   50000.0               85.0
2  Ghanshyam  22.0   45000.0               78.0
3  Dhanshyam  30.0   52000.0               92.0
4      Aditu  29.0   49000.0               88.0
5   Jagadish  40.0   70000.0               95.0
6        Raj  25.0  480000.0               80.0
7     Simran  32.0   58000.0               89.0


In [16]:
#replace with some value without drop
#use fillnae()
#fillna(value,inplace=True)
import pandas as pd
mani_data={
    "Name":['Ram',None,'Ghanshyam','Dhanshyam','Aditu','Jagadish','Raj','Simran'],
    "Age":[28,None,22,30,29,40,25,32],
    "Salary":[50000,None,45000,52000,49000,70000,480000,58000],
    "Performance_Score":[85,None,78,92,88,95,80,89]
}
df=pd.DataFrame(mani_data)
print(df)
df.fillna(0,inplace=True)
print(df)

        Name   Age    Salary  Performance_Score
0        Ram  28.0   50000.0               85.0
1       None   NaN       NaN                NaN
2  Ghanshyam  22.0   45000.0               78.0
3  Dhanshyam  30.0   52000.0               92.0
4      Aditu  29.0   49000.0               88.0
5   Jagadish  40.0   70000.0               95.0
6        Raj  25.0  480000.0               80.0
7     Simran  32.0   58000.0               89.0
        Name   Age    Salary  Performance_Score
0        Ram  28.0   50000.0               85.0
1          0   0.0       0.0                0.0
2  Ghanshyam  22.0   45000.0               78.0
3  Dhanshyam  30.0   52000.0               92.0
4      Aditu  29.0   49000.0               88.0
5   Jagadish  40.0   70000.0               95.0
6        Raj  25.0  480000.0               80.0
7     Simran  32.0   58000.0               89.0


In [19]:
import pandas as pd
mani_data={
    "Name":['Ram',None,'Ghanshyam','Dhanshyam','Aditu','Jagadish','Raj','Simran'],
    "Age":[28,None,22,30,29,40,25,32],
    "Salary":[50000,None,45000,52000,49000,70000,480000,58000],
    "Performance_Score":[85,None,78,92,88,95,80,89]
}
df=pd.DataFrame(mani_data)
df['Age'].fillna(df['Age'].mean(),inplace=True)
df['Salary'].fillna(df['Salary'].mean(),inplace=True)

print(df)


        Name        Age         Salary  Performance_Score
0        Ram  28.000000   50000.000000               85.0
1       None  29.428571  114857.142857                NaN
2  Ghanshyam  22.000000   45000.000000               78.0
3  Dhanshyam  30.000000   52000.000000               92.0
4      Aditu  29.000000   49000.000000               88.0
5   Jagadish  40.000000   70000.000000               95.0
6        Raj  25.000000  480000.000000               80.0
7     Simran  32.000000   58000.000000               89.0


In [ ]:
#inter polution 
#we can fill estimated value that is numeric.
#linear why
   # preserve data integrity 
   #smooth trends (we need continue value)
   #avoid data loss
#interpolate() can find estimate value then it will fill it 
import pandas as pd
mani_data={
    "Name":['Ram','Shyam','Ghanshyam','Dhanshyam','Aditu','Jagadish','Raj','Simran'],
    "Age":[28,None,22,30,29,40,25,32],
    "Salary":[50000,None,45000,52000,49000,70000,480000,58000],
    "Performance_Score":[85,None,78,92,88,95,80,89]
}
df=pd.DataFrame(mani_data)
print(df)
#linear,polynomial,time
df.interpolate(method='linear',axis=0,inplace=True)
#how linear work check linear file



In [20]:
import pandas as pd
data={
    "Time":[1,2,3,4,5],
    "Value":[10,None,30,None,50]
}
df=pd.DataFrame(data)
print("before interpolation")
print(df)

df['Value']=df['Value'].interpolate(method="linear")
print("after interplation")
print(df)




before interpolation
   Time  Value
0     1   10.0
1     2    NaN
2     3   30.0
3     4    NaN
4     5   50.0
after interplation
   Time  Value
0     1   10.0
1     2   20.0
2     3   30.0
3     4   40.0
4     5   50.0


In [21]:
#sorting and aggreation 
# sorting data
#sorting data 1 column sort_values()
#df.sort_values(by="Column name" True/False,inplace=True)

import pandas as  pd 
data={
    "Name":['Arun','Varun','Karun'],
    "Age":[28,34,22],
    "Salary":[10000,20000,30000]
    
}
df=pd.DataFrame(data)
print(df)
df.sort_values(by='Age',ascending=True,inplace=True)
print('sorted age by desceding')
print(df)

    Name  Age  Salary
0   Arun   28   10000
1  Varun   34   20000
2  Karun   22   30000
sorted age by desceding
    Name  Age  Salary
2  Karun   22   30000
0   Arun   28   10000
1  Varun   34   20000


In [22]:
df.sort_values(by=["Age","Salary"],ascending=[True,False],inplace=True)
print(df)

    Name  Age  Salary
2  Karun   22   30000
0   Arun   28   10000
1  Varun   34   20000


In [ ]:
#

## in aggregation summary statistics
## summary statistics
### df["Column name].mean()
### df["column name"].sum()
### df["column name"].min()
### df["column name"].max()



In [23]:
#
import pandas as pd
data={
    "Name":['Arun','Varun','Karun'],
    "Age":[28,34,22],
    "Salary":[10000,20000,30000]
}

df=pd.DataFrame(data)
print(df)
avg_salary=df['Salary'].mean()
print(avg_salary)

    Name  Age  Salary
0   Arun   28   10000
1  Varun   34   20000
2  Karun   22   30000
20000.0


# grouping in data 
# two things how create group 
# how aggregation on the group of data 


In [27]:
import pandas as pd
data={
    "Name":['Arun','Varun','Karun','Narun','Marun'],
    "Age":[28,34,22,34,28],
    "Salary":[10000,20000,30000,52000,480000]
}
df=pd.DataFrame(data)
grouped=df.groupby("Age")["Salary"].sum()
print(grouped)
grouped_name=df.groupby(["Age","Name"])["Salary"].sum()
print(grouped_name)


Age
22     30000
28    490000
34     72000
Name: Salary, dtype: int64
Age  Name 
22   Karun     30000
28   Arun      10000
     Marun    480000
34   Narun     52000
     Varun     20000
Name: Salary, dtype: int64


# merging 


In [37]:
import pandas as pd
df_customers=pd.DataFrame({
    'CustomerId':[1,2,3],
    'Name':['Ramesh','Suresh','Kalpesh']
})

df_orders=pd.DataFrame({
    'CustomerId':[1,2,3],
    'OrderAmount':[250,450,350]
})

df_merged=pd.merge(df_customers,df_orders,on="CustomerId",how='inner')
print('inner join')
print(df_merged)

inner join
   CustomerId     Name  OrderAmount
0           1   Ramesh          250
1           2   Suresh          450
2           3  Kalpesh          350


In [40]:
#🔹 Example (Row-wise concat)
import pandas as pd

df1 = pd.DataFrame({
    "ID": [1, 2],
    "Name": ["Ram", "Shyam"]
})

df2 = pd.DataFrame({
    "ID": [3, 4],
    "Name": ["Geeta", "Simran"]
})

result = pd.concat([df1, df2], ignore_index=True)
print("row wise concat")
print(result)

#🔹 Column-wise concat
print("column wise concat")
result = pd.concat([df1, df2], axis=1)
print(result)


row wise concat
   ID    Name
0   1     Ram
1   2   Shyam
2   3   Geeta
3   4  Simran
column wise concat
   ID   Name  ID    Name
0   1    Ram   3   Geeta
1   2  Shyam   4  Simran


### Merging in Pandas (pd.merge)

In [41]:
emp = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Ram", "Shyam", "Geeta"]
})

salary = pd.DataFrame({
    "ID": [1, 2, 4],
    "Salary": [50000, 60000, 70000]
})

merged = pd.merge(emp, salary, on="ID", how="inner")
print(merged)


   ID   Name  Salary
0   1    Ram   50000
1   2  Shyam   60000


In [ ]:
"""| Type    | Description               |
| ------- | ------------------------- |
| `inner` | Only common rows          |
| `left`  | All left + matching right |
| `right` | All right + matching left |
| `outer` | All rows                  |"""
